image:
  repository: muratkorkmaz24/kafka-producer
  tag: latest
  pullPolicy: IfNotPresent

env:
  KAFKA_BROKER: 192.168.1.55:9092
  KAFKA_TOPIC: test-topic

service:
  type: ClusterIP
  port: 3000

replicaCount: 1
