image:
  repository: muratkorkmaz24/kafka-producer
  tag: latest
  pullPolicy: IfNotPresent

env:
  KAFKA_BROKER: 192.168.1.37:9092
  KAFKA_TOPIC: test-topic

service:
  type: NodePort  # ← Burayı ekliyoruz
  port: 3000

replicaCount: 1
