apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-producer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muratkorkmaz1/kafka-mongo-nodejs
    targetRevision: main
    path: chart/producer
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
